name: EssentialsPE
main: EssentialsPE\Loader
version: 1.0.0
api: 1.0.0
author: iksaku
website: https://github.com/LegendOfMCPE/EssentialsPE

permissions:
    essentials:
        default: op
        description: "Allow to access to every EssentialsPE feature"
        children:
            essentials.ban.exempt:
                default: op
                description: "Prevent the player from being banned"
            essentials.colorchat:
                default: op
                description: "Allow to chat using colors!"
            essentials.command:
                default: op
                description: "Allow to access any EssentialsPE command"
                children:
                    essentials.command.broadcast:
                        default: op
                        description: "Broadcast a message"
                        children:
                            essentials.command.broadcast.use:
                                default: op
                                description: "Broadcast a message"
                            essentials.command.broadcast.permselect:
                                default: op
                                description: "Broadcast a message to players that have a certain permission"
                    essentials.command.burn:
                        default: op
                        description: "Set a player on fire"
                    essentials.command.clearinventory:
                        default: op
                        description: "Clear a player inventory"
                        children:
                            essentials.command.clearinventory.use:
                                default: op
                                description: "Clear your inventory"
                            essentials.command.clearinventory.other:
                                defult: op
                                description: "Clear other's inventory"
                    essentials.command.essentials:
                        default: op
                        description: "See the current Essentials version"
                    essentials.command.extinguish:
                        default: op
                        description: "Extinguish a player"
                        children:
                            essentials.command.extinguish.use:
                                default: op
                                description: "Extinguish yourslef"
                            essentials.command.extinguish.other:
                                default: op
                                description: "Extinguish other players"
                    essentials.command.getpos:
                        default: op
                        description: "Get any player's position"
                        children:
                            essentials.command.getpos.use:
                                default: true
                                description: "Get your current position"
                            essentials.command.getpos.other:
                                default: op
                                description: "Get other player's position"
                    essentials.command.god:
                        default: op
                        description: "Prevent a player to take any damage"
                        children:
                            essentials.command.god.use:
                                default: op
                                decription: "Prevent you to take damage"
                            essentials.command.god.other:
                                default: op
                                decription: "Prevent other player to take damage"
                    essentials.command.heal:
                        default: op
                        description: "Heal yourself or other players"
                        children:
                            essentials.command.heal.use:
                                default: op
                                description: "Heal yourself"
                            essentials.command.heal.other:
                                default: op
                                description: "Heal other players"
                    essentials.command.home:
                        default: op
                        description: "Teleports you to your or another player's home"
                        children:
                            essentials.command.home.use:
                                default: true
                                description: "Teleports you to your home"
                            essentials.command.home.other:
                                default: op
                                description: "Teleports you to another player's home"
                    essentials.command.sethome:
                        default: true
                        description: "Sets your home"
                        children:
                            essentials.command.sethome.use:
                                default: true
                                description: "Sets your home"
                    essentials.command.item:
                        default: op
                        description: "Gives yourself an item"
                    essentials.command.kickall:
                        default: op
                        description: "Kick all the online players except the sender"
                    essentials.command.more:
                        default: op
                        description: "Get a stack of the item you're holding"
                    essentials.command.mute:
                        default: op
                        description: "Mute a player from the chat"
                        chldren:
                            essentials.command.mute.use:
                                default: op
                                description: "Let you mute a player"
                            essentials.command.mute.exempt:
                                default: op
                                description: "Prevent a player from being muted"
                    essentials.command.nick:
                        default: op
                        description: "Change your or others name"
                        children:
                            essentials.command.nick.use:
                                default: true
                                description: "Change your name"
                            essentials.command.nick.other:
                                default: op
                                desctiption: "Change others name"
                    essentials.command.powertool:
                        default: op
                        description: "Allow to toggle and use PowerTool"
                    essentials.command.powertooltoggle:
                        default: op
                        description: "Allow to disable PowerTool from all the items (of a player)"
                    essentials.command.pvp:
                        default: true
                        description: "Toggle PvP on/off"
                    essentials.command.realname:
                        default: op
                        description: "See a player's realname"
                    essentials.command.repair:
                        default: op
                        description: "Repair the item you're holding"
                    essentials.command.seen:
                        default: op
                        description: "Check player's last online time"
                    essentials.command.setspawn:
                        default: op
                        description: "Change your server's general spawn"
                    essentials.command.tempban:
                        default: op
                        description: "Temporary bans a player"
                    essentials.command.top:
                        default: op
                        description: "Teleport to the highest block above you"
                    essentials.command.vanish:
                        default: op
                        description: "Hide yourself or another player"
                        children:
                            essentials.command.vanish.use:
                                default: op
                                description: "Hide yourself from other players"
                            essentials.command.vanish.other:
                                default: op
                                description: "Hide other players"
                    essentials.command.warp:
                        default: op
                        description: "Warp managment permissions"
                        children:
                            essentials.command.warp.use:
                                default: true
                                description: "Teleport to a warp!"
                            essentials.command.warp.other:
                                default: op
                                description: "Teleport other players to a warp"
                            essentials.command.warp.remove:
                                default: op
                                description: "Close a warp"
                            essentials.command.warp.set:
                                default: op
                                description: "Open a warp"
