# EssentialsPE configuration
# This configuration flie let you modify how EssentialsPE work with some features

# This option let you disable player damage when they're AFK
safe-afk: true
# Time until the server kick an AFK player (in seconds)
# Set it to -1 for not timeout
auto-afk-kick: 300

# Let you configure the size of a stack that players (with permission) can get (via /more or /item)
oversized-stacks: 64

# Let you set a limit for the /near command to search for players (in meters)
near-radius-limit: 200
# Let you set a default value to search for players (it can't be higher than the default limit)
near-default-radius: 200

# This option let you enable color codes in the server, but keep in mind that the client may not support them
enable-custom-colors: false

updater:
  update-checks: # this is about the subcommand `/essentials update check`
    # currently, we only check releases and pre-releases
    - channel: release # this must be one of "release" or "pre-release"
      actions:
        # The following lines will be done in order.
        # Add, modify or remove the lines to change.
        # Each line must be one of "notify-console", "notify-ops", "download", "install&stop"
        # "install&stop" must be run after "download"
        - notify-console
        - notify-ops # this notifies all online players with the permission essentials.essentials.notifyupdate
        - download
    - channel: pre-release
      actions:
        - notify-console
